default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-yaml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.246
    hooks:
      - id: ruff
        args:
        - --fix
  - repo: https://github.com/python/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        additional_dependencies:
          - bioregistry==0.8.3
          - bioversions==0.5.98
          - nxontology==0.4.1
          - pandas==1.5.3
          - pytest
  - repo: https://github.com/python-poetry/poetry
    rev: '1.3.2'  # pre-commit autoupdate will not update to the latest version
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [--check]
