name: Schedule NXOntology Creation
on:
  schedule:
    - cron: '0 0 1 * *'  # https://crontab.guru/#0_0_1_*_*
  workflow_dispatch:
jobs:
  schedule_create:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
    - name: Create test
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: create.yaml
        inputs: '{ "source": "test", "overwrite": false }'
