name: Test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install poetry
      shell: bash
      run: pip install poetry
    - name: Install dependencies
      shell: bash
      run: poetry install --ansi
    - name: Run pre-commit
      uses: pre-commit/action@v2.0.3
    - name: Run tests
      run: poetry run pytest --color=yes
